---
- name: Deploy new Debian or Ubuntu VPS
  hosts: xenservers
  remote_user: root
  vars_files:
    - xenserver_vars.yml

  tasks:
    - name: Get the IP address of the VM
      shell: xe vm-list uuid=3f64b820-eb74-0703-dcb9-a4e23b9ef7cf params=networks | grep -oP "0/ipv4/0:\s+\K\w+.\w+.\w+.\w+"
      register: ipaddr

    - debug:
        msg: "Ip Address: {{ ipaddr.stdout }}"

