---
- name: Deploy new Debian or Ubuntu VPS
  hosts: xenservers
  remote_user: root
  vars_files:
    - xenserver_vars.yml

  tasks:

    - name: Load VPS specs for chosen type
      set_fact:
        memory: "{{ lookup('csvfile', '{{ vps_type }} file=vmtypes.csv delimiter=, col=3') }}"
        cpu_weight: "{{ lookup('csvfile', '{{ vps_type }} file=vmtypes.csv delimiter=, col=2') }}"
        disksize: "{{ lookup('csvfile', '{{ vps_type }} file=vmtypes.csv delimiter=, col=1') }}"

    - name: Get UUID of share SR
      command: xe sr-list name-label="{{ sr_name }}" --minimal
      register: sruuid

    - name: Get the UUID of the VM template
      command: xe template-list name-label="{{ vm_template }}" --minimal
      register: templateuuid

    - name: Get the UUID of the network
      command: xe network-list name-label="{{ network_name }}" --minimal
      register: networkuuid

    - name: Deploy new VM
      command: xe vm-install template={{ templateuuid.stdout }} new-name-label="{{ vm_name }} - {{ vps_type }}" sr-uuid={{ sruuid.stdout }}
      register: vmuuid

    - name: Set vcpu priority
      command: xe vm-param-set VCPUs-params:weight={{ cpu_weight }} uuid={{ vmuuid.stdout }}

    - name: Set vcpu count max
      command: xe vm-param-set VCPUs-max={{ vcpu_count }} uuid={{ vmuuid.stdout }}
      when: vcpu_count >= "2"

    - name: Set vcpu count at startup
      command: xe vm-param-set VCPUs-at-startup={{ vcpu_count }} uuid={{ vmuuid.stdout }}
      when: vcpu_count >= "2"

    - name: Get the UUID of the disk
      command: xe vm-disk-list vbd-params=device=xvda uuid={{ vmuuid.stdout }} --minimal
      register: vdiuuid

    - name: Set memory
      command: xe vm-memory-limits-set uuid={{ vmuuid.stdout }} dynamic-min="{{ memory }}" dynamic-max="{{ memory }}" static-max="{{ memory }}" static-min="{{ memory }}"

    - name: Boot VM and start preseed installation
      command: xe vm-start uuid={{ vmuuid.stdout }}

    - pause:
        minutes: 1

    - name: Get the IP address of the VM
      shell: xe vm-list uuid={{ vmuuid.stdout }} params=networks | grep -oP "0/ipv4/0:\s+\K\w+.\w+.\w+.\w+"
      register: ipaddr

    - debug:
        msg: "Ip Address: {{ ipaddr.stdout }}"

    - name: Update the VMs name
      command: xe vm-param-set name-label="{{ vm_name }} - {{ ipaddr.stdout }} - {{ vps_type }}" uuid={{ vmuuid.stdout }}

    - name: Add host to runtime inventory
      add_host:
        name="{{ ipaddr.stdout }}"
        groups="deployed_vms"
